name: PHPUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, json

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Regenerate Composer autoload
        run: composer dump-autoload

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml --colors=always